spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway.enabled: true
  jpa:
    open-in-view: false
hibernate:
  dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  packages-to-scan: 'com.modsen.api.model.entity'
  lucene-version: 'LATEST'
  lucene-root-directory: './temp/lucene/indices'